[2025-04-04T18:01:50.223+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T18:01:50.251+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_v2.train_ml_model manual__2025-04-04T18:01:18.155298+00:00 [queued]>
[2025-04-04T18:01:50.265+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_v2.train_ml_model manual__2025-04-04T18:01:18.155298+00:00 [queued]>
[2025-04-04T18:01:50.266+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-04T18:01:50.282+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train_ml_model> on 2025-04-04 18:01:18.155298+00:00
[2025-04-04T18:01:50.290+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4957) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-04T18:01:50.292+0000] {standard_task_runner.py:63} INFO - Started process 4959 to run task
[2025-04-04T18:01:50.292+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_v2', 'train_ml_model', 'manual__2025-04-04T18:01:18.155298+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/dag_tmdb.py', '--cfg-path', '/tmp/tmpewtpw2wy']
[2025-04-04T18:01:50.295+0000] {standard_task_runner.py:91} INFO - Job 132: Subtask train_ml_model
[2025-04-04T18:01:50.349+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_v2.train_ml_model manual__2025-04-04T18:01:18.155298+00:00 [running]> on host 1b0019c2839f
[2025-04-04T18:01:50.464+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_v2' AIRFLOW_CTX_TASK_ID='train_ml_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T18:01:18.155298+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T18:01:18.155298+00:00'
[2025-04-04T18:01:50.466+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T18:01:52.152+0000] {warnings.py:110} WARNING - /opt/***/dags/dag_tmdb.py:820: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

[2025-04-04T18:01:52.683+0000] {dag_tmdb.py:899} INFO - Modelo ML entrenado y guardado en /opt/***/data/movie_analytics/ml_model_v2_20250404_180152
[2025-04-04T18:01:52.683+0000] {dag_tmdb.py:900} INFO - Métricas del modelo - MSE: 20112.9701, R²: -1.1902
[2025-04-04T18:01:52.712+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/data/movie_analytics/ml_model_v2_20250404_180152
[2025-04-04T18:01:52.713+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T18:01:52.737+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_v2, task_id=train_ml_model, execution_date=20250404T180118, start_date=20250404T180150, end_date=20250404T180152
[2025-04-04T18:01:52.813+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-04T18:01:52.836+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-04T18:01:52.838+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
