[2025-04-05T12:06:07.203+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T12:06:07.235+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.generate_visualizations scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-05T12:06:07.246+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.generate_visualizations scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-05T12:06:07.247+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-05T12:06:07.269+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2025-04-05 00:00:00+00:00
[2025-04-05T12:06:07.276+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1004) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-05T12:06:07.278+0000] {standard_task_runner.py:63} INFO - Started process 1006 to run task
[2025-04-05T12:06:07.279+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_streamlit', 'generate_visualizations', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmp2kpxkhvn']
[2025-04-05T12:06:07.282+0000] {standard_task_runner.py:91} INFO - Job 276: Subtask generate_visualizations
[2025-04-05T12:06:07.345+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_streamlit.generate_visualizations scheduled__2025-04-05T00:00:00+00:00 [running]> on host bb6ca4ffe8d9
[2025-04-05T12:06:07.499+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_streamlit' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-05T12:06:07.501+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T12:06:10.779+0000] {tmdb_pipeline.py:1716} ERROR - Error al leer datos de PostgreSQL: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-05T12:06:10.785+0000] {tmdb_pipeline.py:1717} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 1684, in generate_visualizations
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-05T12:06:12.612+0000] {tmdb_pipeline.py:1790} INFO - Visualizaciones guardadas en /opt/***/data/movie_analytics/visualizations_v3_20250405_120610
[2025-04-05T12:06:12.643+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/data/movie_analytics/visualizations_v3_20250405_120610
[2025-04-05T12:06:12.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T12:06:12.685+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_streamlit, task_id=generate_visualizations, execution_date=20250405T000000, start_date=20250405T120607, end_date=20250405T120612
[2025-04-05T12:06:12.764+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T12:06:12.807+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T12:06:12.809+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
