[2025-04-05T00:09:34.375+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T00:09:34.396+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.generate_visualizations manual__2025-04-05T00:09:01.823700+00:00 [queued]>
[2025-04-05T00:09:34.404+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.generate_visualizations manual__2025-04-05T00:09:01.823700+00:00 [queued]>
[2025-04-05T00:09:34.405+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-05T00:09:34.418+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2025-04-05 00:09:01.823700+00:00
[2025-04-05T00:09:34.424+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=166) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-05T00:09:34.426+0000] {standard_task_runner.py:63} INFO - Started process 168 to run task
[2025-04-05T00:09:34.426+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_streamlit', 'generate_visualizations', 'manual__2025-04-05T00:09:01.823700+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmpmohdxxn3']
[2025-04-05T00:09:34.429+0000] {standard_task_runner.py:91} INFO - Job 252: Subtask generate_visualizations
[2025-04-05T00:09:34.476+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_streamlit.generate_visualizations manual__2025-04-05T00:09:01.823700+00:00 [running]> on host 4ac21fa6114e
[2025-04-05T00:09:34.607+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_streamlit' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:09:01.823700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T00:09:01.823700+00:00'
[2025-04-05T00:09:34.609+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T00:09:35.273+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-04-05T00:09:36.652+0000] {tmdb_pipeline.py:1674} ERROR - Error al leer datos de PostgreSQL: connection to server at "movie_postgres" (172.19.0.3), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-05T00:09:36.654+0000] {tmdb_pipeline.py:1675} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 1642, in generate_visualizations
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.3), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-05T00:09:37.873+0000] {tmdb_pipeline.py:1748} INFO - Visualizaciones guardadas en /opt/***/data/movie_analytics/visualizations_v3_20250405_000936
[2025-04-05T00:09:37.888+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/data/movie_analytics/visualizations_v3_20250405_000936
[2025-04-05T00:09:37.890+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T00:09:37.910+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_streamlit, task_id=generate_visualizations, execution_date=20250405T000901, start_date=20250405T000934, end_date=20250405T000937
[2025-04-05T00:09:37.979+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T00:09:38.008+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T00:09:38.010+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
