[2025-04-01T19:29:47.943+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-01T19:29:47.971+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline.generate_visualizations scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-01T19:29:47.980+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline.generate_visualizations scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-01T19:29:47.980+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-01T19:29:47.996+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2025-04-01 00:00:00+00:00
[2025-04-01T19:29:48.005+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-01T19:29:48.007+0000] {standard_task_runner.py:63} INFO - Started process 189 to run task
[2025-04-01T19:29:48.008+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline', 'generate_visualizations', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmphiqwrzqo']
[2025-04-01T19:29:48.010+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask generate_visualizations
[2025-04-01T19:29:48.067+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline.generate_visualizations scheduled__2025-04-01T00:00:00+00:00 [running]> on host 29a2839b1f8c
[2025-04-01T19:29:48.151+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-01T19:29:48.152+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-01T19:29:48.781+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-04-01T19:29:50.761+0000] {tmdb_pipeline.py:547} ERROR - Error al leer datos de PostgreSQL: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-01T19:29:51.766+0000] {tmdb_pipeline.py:620} INFO - Visualizaciones guardadas en /opt/***/data/movie_analytics/visualizations_20250401_192950
[2025-04-01T19:29:51.819+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/data/movie_analytics/visualizations_20250401_192950
[2025-04-01T19:29:51.820+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-01T19:29:51.922+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline, task_id=generate_visualizations, execution_date=20250401T000000, start_date=20250401T192947, end_date=20250401T192951
[2025-04-01T19:29:51.972+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-01T19:29:52.005+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-01T19:29:52.006+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
