[2025-04-12T15:07:57.008+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-12T15:07:57.030+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-12T15:07:57.038+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-12T00:00:00+00:00 [queued]>
[2025-04-12T15:07:57.038+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2025-04-12T15:07:57.051+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_kafka_data> on 2025-04-12 00:00:00+00:00
[2025-04-12T15:07:57.057+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=11007) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T15:07:57.059+0000] {standard_task_runner.py:63} INFO - Started process 11009 to run task
[2025-04-12T15:07:57.059+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_v2', 'process_kafka_data', 'scheduled__2025-04-12T00:00:00+00:00', '--job-id', '1122', '--raw', '--subdir', 'DAGS_FOLDER/dag_tmdb.py', '--cfg-path', '/tmp/tmpeqdp1xnk']
[2025-04-12T15:07:57.062+0000] {standard_task_runner.py:91} INFO - Job 1122: Subtask process_kafka_data
[2025-04-12T15:07:57.117+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-12T00:00:00+00:00 [running]> on host d6f276a13019
[2025-04-12T15:07:57.215+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_v2' AIRFLOW_CTX_TASK_ID='process_kafka_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T00:00:00+00:00'
[2025-04-12T15:07:57.216+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-12T15:07:57.336+0000] {dag_tmdb.py:283} INFO - Iniciando proceso de consumo de datos de Kafka
[2025-04-12T15:07:57.339+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-12T15:07:57.343+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <checking_api_versions_recv> [IPv4 ('172.19.0.6', 9093)]>: Broker version identified as 2.6
[2025-04-12T15:07:57.343+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-12T15:07:57.344+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('tmdb_data',)
[2025-04-12T15:07:57.345+0000] {dag_tmdb.py:295} INFO - Consumidor conectado a Kafka, esperando mensajes en 'tmdb_data'...
[2025-04-12T15:07:57.345+0000] {dag_tmdb.py:339} INFO - Intento 1/3 de obtener mensajes
[2025-04-12T15:07:57.348+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-12T15:07:57.348+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-12T15:07:57.349+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-12T15:07:57.453+0000] {cluster.py:393} INFO - Group coordinator for ***_consumer_group_v2 is ('coordinator-1001', 'kafka', 9093, None)
[2025-04-12T15:07:57.454+0000] {base.py:729} INFO - Discovered coordinator coordinator-1001 for group ***_consumer_group_v2
[2025-04-12T15:07:57.455+0000] {base.py:780} INFO - Starting new heartbeat thread
[2025-04-12T15:07:57.456+0000] {consumer.py:361} INFO - Revoking previously assigned partitions () for group ***_consumer_group_v2
[2025-04-12T15:07:57.458+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-12T15:07:57.459+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-12T15:07:57.560+0000] {base.py:489} INFO - (Re-)joining group ***_consumer_group_v2
[2025-04-12T15:07:57.566+0000] {base.py:552} INFO - Elected group leader -- performing partition assignments using range
[2025-04-12T15:07:57.569+0000] {base.py:380} INFO - Successfully joined group ***_consumer_group_v2 with generation 17
[2025-04-12T15:07:57.570+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('tmdb_data', 0)]
[2025-04-12T15:07:57.571+0000] {consumer.py:252} INFO - Setting newly assigned partitions (('tmdb_data', 0),) for group ***_consumer_group_v2
[2025-04-12T15:08:02.348+0000] {dag_tmdb.py:352} INFO - No se recibieron suficientes mensajes, esperando... (0 hasta ahora)
[2025-04-12T15:08:04.349+0000] {dag_tmdb.py:339} INFO - Intento 2/3 de obtener mensajes
[2025-04-12T15:08:09.352+0000] {dag_tmdb.py:352} INFO - No se recibieron suficientes mensajes, esperando... (0 hasta ahora)
[2025-04-12T15:08:11.354+0000] {dag_tmdb.py:339} INFO - Intento 3/3 de obtener mensajes
[2025-04-12T15:08:16.358+0000] {dag_tmdb.py:352} INFO - No se recibieron suficientes mensajes, esperando... (0 hasta ahora)
[2025-04-12T15:08:18.360+0000] {dag_tmdb.py:357} WARNING - No se recibieron mensajes de Kafka. Usando datos de ejemplo.
[2025-04-12T15:08:18.360+0000] {dag_tmdb.py:378} INFO - Procesando 1 mensajes con Pandas
[2025-04-12T15:08:18.386+0000] {dag_tmdb.py:427} INFO - Datos procesados guardados en /opt/***/data/movie_analytics/processed_movies_v2.csv
[2025-04-12T15:08:18.415+0000] {base.py:794} INFO - Stopping heartbeat thread
[2025-04-12T15:08:21.417+0000] {base.py:995} WARNING - Heartbeat thread did not fully terminate during close
[2025-04-12T15:08:21.418+0000] {base.py:823} INFO - Leaving consumer group (***_consumer_group_v2).
[2025-04-12T15:08:21.423+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-12T15:08:21.424+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-12T15:08:21.425+0000] {python.py:237} INFO - Done. Returned value was: 1
[2025-04-12T15:08:21.425+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-12T15:08:21.447+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_v2, task_id=process_kafka_data, execution_date=20250412T000000, start_date=20250412T150757, end_date=20250412T150821
[2025-04-12T15:08:21.472+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-12T15:08:21.497+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-12T15:08:21.498+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
